/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-03-10

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "hardware.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/



int main(void)
{
	/* Call peripheral initializations */
	init_clocks();
	init_led_pins();
	init_button_pin();
	init_serial_USART1();
	init_timer_6();

	/* some variables for running light algorithm */
	uint32_t runing_light_data = 1;			/* Will hold info of which LED to turn on*/
	uint32_t runing_light_dirrection = 0;	/*Will hold info of running lights running direction*/

	send_string_USART1("Begin");			/* Send info to terminal of algorithm starting */
	tunr_on_led(runing_light_data);			/* Makes sure first led is turned on when algorithm starts */

	/* Infinite loop */
	while (1)
	{
		/* TEST SERIAL */
		uint8_t symbol = receive_byte_USART1();	/* Receive data if available */
		if(symbol){
			send_string_USART1("Data received:");
			send_byte_USART1(symbol);			/* Send back received symbol */
			send_byte_USART1('\n');				/* new line and return to start of line*/
			send_byte_USART1('\r');
			symbol = 0;							/* Rest received value */
		} /* end of symbol received */

		/* TEST BUTTON */
		if(BTN_RD){								/* Poll if pushbutton pressed */
				for(int i=0;i<50000;i++); 		/* Really primitive de-bounce for button*/
				if(BTN_RD){						/* Repeat poll if pushbutton pressed */
					runing_light_dirrection ^= 1;					/* when pressed changes direction */
					send_string_USART1("Button pressed");			/* Send info to serial console */
				}/* end of  if(BTN_RD) */
			}
		/* end of test button */

		/* TEST LIGHT */
		/* Delay for LED next state, default 500ms, interrupt insures that function
		 * will be executed as soon as this statement is checked, testing timer
		 * value (if(TIM6->CNT >= 0xc350)) worked unstable - because of polling some iterations were skipped
		 * */
		if(tim6_int_counter>0){												/* Test interrupt counter */
			if(runing_light_dirrection == 0){								/* Check one direction */
				runing_light_data = runing_light_data << 1;					/* Set position of next LED */
				if (runing_light_data>MAX_LED) runing_light_data = MIN_LED; /* Reset value if end reached */
			}
			else{															/* Check other direction */
				runing_light_data = runing_light_data >> 1;					/* Set position of next LED */
				if (runing_light_data<=MIN_LED) runing_light_data=MAX_LED;}	/* Reset value if end reached */
			tunr_on_led(runing_light_data);									/* Turns on next led in line, whichever direction */
			tim6_int_counter = 0;											/* Reset timer counter*/
		}/* end of if(tim6_int_counter>0) */

	}	/* end of while(1) */
}	/* end of main */
