/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-03-10

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "hardware.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

	init_clocks();
	led_pin_setup();
	//test_leds();
	button_pin_setup();
	init_serial_USART1();

  /* Infinite loop */

	send_string_USART1("Begin");
	while (1)
	{
		uint8_t symbol = receive_byte_USART1();	/* Receive data if available */
		if(symbol){
			if(symbol=='q'){
				test_leds();
			}
			send_string_USART1("Data received:");
			send_byte_USART1(symbol);			/* Send back received symbol */
			send_byte_USART1('\n');		/* new line and return to start of line*/
			send_byte_USART1('\r');
			symbol = 0;					/* Rest received value */
		} /* end of symbol received */


		/* test button */
		if(GPIOC->IDR&(1<<13)){		/* check when pin is low */
			GPIOA->ODR &=0<<5; 		/* switches that LED off*/
		}
		else{
			GPIOA->ODR |= 0b1<<5;		/* turn on LED on PORTA pin 5 */
			send_byte_USART1('a');	/* send one symbol when button is pressed */
		} /* end of test button */

	}	/* end of while(1) */
}	/* end of main */
